DragonCorpus/DragonCorpus/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^management/', include('management.urls',  namespace='management')),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

    # reset password
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete', ),
]

DragonCorpus/accounts/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from accounts import user
from accounts import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, PasswordResetForm
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', user.login, name='login'),
    url(r'^logout/$', user.logout, name='logout'),
    url(r'^change_password/$', user.change_password, name='change_password'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
]

DragonCorpus/management/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    #login
    url(r'^index/$',views.index,name='index'),
    url(r'^(?P<project_id>\w+)/project_overview_detail/$',views.project_overview_detail,name='project_overview_detail'),
    url(r'^project_overview_detail_table/$',views.project_overview_detail_table,name='project_overview_detail_table'),
    url(r'^testsuit_overview_detail_table/$', views.testsuit_overview_detail_table, name='testsuit_overview_detail_table'),
    url(r'^utterance_table/$', views.utterance_table, name='utterance_table'),
    url(r'^(?P<testsuit_id>\w+)/testsuit_overview_detail/$', views.testsuit_overview_detail,name='testsuit_overview_detail'),
    url(r'^new_project/$',views.new_project,name='new_project'),
    url(r'^new_testsuit/$',views.new_testsuit,name='new_testsuit'),
    url(r'^utterance/$', views.utterance, name='utterance'),
    url(r'^upload_hrl/$', views.upload_hrl, name='upload_hrl'),
    url(r'^project_and_testsuit_overview_detail/$', views.project_and_testsuit_overview_detail, name='project_and_testsuit_overview_detail'),
    #filter
    url(r'^get_all_intent/$', views.get_all_intent, name='get_all_intent'),
    url(r'^get_testsuit_all_intent/$', views.get_testsuit_all_intent, name='get_testsuit_all_intent'),

    #error
    url(r'^error_page/$', views.error_page, name='error_page'),

    #delete testsuit
    url(r'^delete_testsuit/$', views.delete_testsuit,name='delete_tesuit'),
    # add testSuit
    url(r'^add_testsuit/$', views.add_testsuit, name='add_testsuit'),
    # delete_testsuit_item
    url(r'^delete_testsuit_item/$', views.delete_testsuit_item, name='delete_testsuit_item'),
    #download_testsuit
    url(r'^download_testsuit/$', views.download_testsuit, name='download_testsuit'),
    url(r'^zip_download/$', views.zip_download, name='zip_download'),
    #upload audio
    url(r'^upload_utterance_table/$', views.upload_utterance_table, name='upload_utterance_table'),

]

DragonCorpus/templates/index_page_content.html
<div class="page-content">

    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->

    <!--<div id="portlet-config" class="modal hide">-->

    <!--<div class="modal-header">-->

    <!--<button data-dismiss="modal" class="close" type="button"></button>-->

    <!--<h3>Widget Settings</h3>-->

    <!--</div>-->

    <!--<div class="modal-body">-->

    <!--Widget settings form goes here-->

    <!--</div>-->

    <!--</div>-->

    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

    <!-- BEGIN PAGE CONTAINER-->

    <div class="container-fluid">

        <!-- BEGIN PAGE HEADER-->

        <div class="row-fluid">

            <div class="span12">

                <!-- BEGIN STYLE CUSTOMIZER -->

                <!--{% include 'base/theme.html' %}-->

                <!-- END BEGIN STYLE CUSTOMIZER -->

                <!-- BEGIN PAGE TITLE & BREADCRUMB-->

                <h3 class="page-title">

                    Dashboard
                    <small>statistics and more</small>

                </h3>

                <ul class="breadcrumb">

                    <li>

                        <i class="icon-home"></i>

                        <a href="{% url 'management:index'%}">Home</a>

                        <i class="icon-angle-right"></i>

                    </li>

                    <li><a href="#">Dashboard</a></li>

                    <li class="pull-right no-text-shadow">

                        <div id="dashboard-report-range"
                             class="dashboard-date-range tooltips no-tooltip-on-touch-device responsive" data-tablet=""
                             data-desktop="tooltips" data-placement="top"
                             data-original-title="Change dashboard date range">

                            <i class="icon-calendar"></i>

                            <span></span>

                            <i class="icon-angle-down"></i>

                        </div>

                    </li>

                </ul>

                <!-- END PAGE TITLE & BREADCRUMB-->

            </div>

        </div>

        <!-- END PAGE HEADER-->

        <div id="dashboard">

            <!-- BEGIN DASHBOARD STATS -->

            <div class="row-fluid">

                <div class="span3 responsive" data-tablet="span6" data-desktop="span3">

                    <div class="dashboard-stat blue">

                        <div class="visual">

                            <i class="icon-leaf"></i>

                        </div>

                        <div class="details">

                            <div class="number">

                                {{rrt_project_count}}

                            </div>

                            <div class="desc">

                                Project

                            </div>

                        </div>

                        <a class="more" href="#">

                            <i class="m-icon-swapright m-icon-white"></i>

                        </a>

                    </div>

                </div>

                <div class="span3 responsive" data-tablet="span6" data-desktop="span3">

                    <div class="dashboard-stat green">

                        <div class="visual">

                            <i class="icon-magnet"></i>

                        </div>

                        <div class="details">

                            <div class="number">{{rrt_domain_count}}</div>

                            <div class="desc">Domain</div>

                        </div>

                        <a class="more" href="#">

                            <i class="m-icon-swapright m-icon-white"></i>

                        </a>

                    </div>

                </div>

                <div class="span3 responsive" data-tablet="span6  fix-offset" data-desktop="span3">

                    <div class="dashboard-stat purple">

                        <div class="visual">

                            <i class="icon-tasks"></i>

                        </div>

                        <div class="details">

                            <div class="number">{{rrt_intent_count}}</div>

                            <div class="desc">Intent</div>

                        </div>

                        <a class="more" href="#">

                            <i class="m-icon-swapright m-icon-white"></i>

                        </a>

                    </div>

                </div>

                <div class="span3 responsive" data-tablet="span6" data-desktop="span3">

                    <div class="dashboard-stat yellow">

                        <div class="visual">

                            <i class="icon-pencil"></i>

                        </div>

                        <div class="details">

                            <div class="number">{{rrt_audio_count}}</div>

                            <div class="desc">Audio</div>

                        </div>

                        <a class="more" href="#">

                            <i class="m-icon-swapright m-icon-white"></i>

                        </a>

                    </div>

                </div>

            </div>

            <!-- END DASHBOARD STATS -->

            <div class="clearfix"></div>

            <div class="row-fluid">

                <div class="span6">

                    <!-- BEGIN PORTLET-->

                    <div class="portlet solid bordered light-grey">

                        <div class="portlet-title">

                            <div class="caption"><i class="icon-bar-chart"></i>Site Visits</div>

                            <div class="tools">

                                <div class="btn-group pull-right" data-toggle="buttons-radio">

                                    <a href="" class="btn mini">Users</a>

                                    <a href="" class="btn mini active">Feedbacks</a>

                                </div>

                            </div>

                        </div>

                        <div class="portlet-body">

                            <div id="site_statistics_loading">

                                <img src="/static/media/image/loading.gif" alt="loading"/>

                            </div>

                            <div id="site_statistics_content" class="hide">

                                <div id="site_statistics" class="chart"></div>

                            </div>

                        </div>

                    </div>

                    <!-- END PORTLET-->

                </div>

                <div class="span6">

                    <!-- BEGIN PORTLET-->

                    <div class="portlet solid light-grey bordered">

                        <div class="portlet-title">

                            <div class="caption"><i class="icon-bullhorn"></i>Activities</div>

                            <div class="tools">

                                <div class="btn-group pull-right" data-toggle="buttons-radio">

                                    <a href="" class="btn blue mini active">Users</a>

                                    <a href="" class="btn blue mini">Orders</a>

                                </div>

                            </div>

                        </div>

                        <div class="portlet-body">

                            <div id="site_activities_loading">

                                <img src="/static/media/image/loading.gif" alt="loading"/>

                            </div>

                            <div id="site_activities_content" class="hide">

                                <div id="site_activities" style="height:100px;"></div>

                            </div>

                        </div>

                    </div>

                    <!-- END PORTLET-->

                    <!-- BEGIN PORTLET-->

                    <div class="portlet solid bordered light-grey">

                        <div class="portlet-title">

                            <div class="caption"><i class="icon-signal"></i>Server Load</div>

                            <div class="tools">

                                <div class="btn-group pull-right" data-toggle="buttons-radio">

                                    <a href="" class="btn red mini active">

                                        <span class="hidden-phone">Database</span>

                                        <span class="visible-phone">DB</span></a>

                                    <a href="" class="btn red mini">Web</a>

                                </div>

                            </div>

                        </div>

                        <div class="portlet-body">

                            <div id="load_statistics_loading">

                                <img src="/static/media/image/loading.gif" alt="loading"/>

                            </div>

                            <div id="load_statistics_content" class="hide">

                                <div id="load_statistics" style="height:108px;"></div>

                            </div>

                        </div>

                    </div>

                    <!-- END PORTLET-->

                </div>

            </div>

            <div class="clearfix"></div>

            <div class="row-fluid">

                <div class="span6">

                    <div class="portlet box purple">

                        <div class="portlet-title">

                            <div class="caption"><i class="icon-calendar"></i>General Stats</div>

                            <div class="actions">

                                <a href="javascript:;" class="btn yellow easy-pie-chart-reload"><i
                                        class="icon-repeat"></i> Reload</a>

                            </div>

                        </div>

                        <div class="portlet-body">

                            <div class="row-fluid">

                                <div class="span4">

                                    <div class="easy-pie-chart">

                                        <div class="number transactions" data-percent="55"><span>+55</span>%</div>

                                        <a class="title" href="#">Transactions <i class="m-icon-swapright"></i></a>

                                    </div>

                                </div>

                                <div class="margin-bottom-10 visible-phone"></div>

                                <div class="span4">

                                    <div class="easy-pie-chart">

                                        <div class="number visits" data-percent="85"><span>+85</span>%</div>

                                        <a class="title" href="#">New Visits <i class="m-icon-swapright"></i></a>

                                    </div>

                                </div>

                                <div class="margin-bottom-10 visible-phone"></div>

                                <div class="span4">

                                    <div class="easy-pie-chart">

                                        <div class="number bounce" data-percent="46"><span>-46</span>%</div>

                                        <a class="title" href="#">Bounce <i class="m-icon-swapright"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

                <div class="span6">

                    <div class="portlet box blue">

                        <div class="portlet-title">

                            <div class="caption"><i class="icon-calendar"></i>Server Stats</div>

                            <div class="tools">

                                <a href="" class="collapse"></a>

                                <a href="#portlet-config" data-toggle="modal" class="config"></a>

                                <a href="" class="reload"></a>

                                <a href="" class="remove"></a>

                            </div>

                        </div>

                        <div class="portlet-body">

                            <div class="row-fluid">

                                <div class="span4">

                                    <div class="sparkline-chart">

                                        <div class="number" id="sparkline_bar"></div>

                                        <a class="title" href="#">Network <i class="m-icon-swapright"></i></a>

                                    </div>

                                </div>

                                <div class="margin-bottom-10 visible-phone"></div>

                                <div class="span4">

                                    <div class="sparkline-chart">

                                        <div class="number" id="sparkline_bar2"></div>

                                        <a class="title" href="#">CPU Load <i class="m-icon-swapright"></i></a>

                                    </div>

                                </div>

                                <div class="margin-bottom-10 visible-phone"></div>

                                <div class="span4">

                                    <div class="sparkline-chart">

                                        <div class="number" id="sparkline_line"></div>

                                        <a class="title" href="#">Load Rate <i class="m-icon-swapright"></i></a>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>

    <!-- END PAGE CONTAINER-->

</div>

DragonCorpus/templates/new_project_page_content.html
<div class="page-content">

    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->

    <!--<div id="portlet-config" class="modal hide">-->

    <!--<div class="modal-header">-->

    <!--<button data-dismiss="modal" class="close" type="button"></button>-->

    <!--<h3>portlet Settings</h3>-->

    <!--</div>-->

    <!--<div class="modal-body">-->

    <!--<p>Here will be a configuration form</p>-->

    <!--</div>-->

    <!--</div>-->

    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

    <!-- BEGIN PAGE CONTAINER-->

    <div class="container-fluid">

        <!-- BEGIN PAGE HEADER-->

        <div class="row-fluid">

            <div class="span12">

                <!-- BEGIN STYLE CUSTOMIZER -->

                <!--{% include 'base/theme.html' %}-->

                <!-- END BEGIN STYLE CUSTOMIZER -->

                <h3 class="page-title">

                    Add New Project

                    <small></small>

                </h3>

                <ul class="breadcrumb">

                    <li>

                        <i class="icon-home"></i>

                        <a href="{% url 'management:index'%}">Home</a>

                        <span class="icon-angle-right"></span>

                    </li>

                    <li>

                        <a href="#">New Project</a>

                        <span class="icon-angle-right"></span>

                    </li>

                    <li><a href="#">Add</a></li>

                </ul>

            </div>

        </div>

        <!-- END PAGE HEADER-->

        <!-- BEGIN PAGE CONTENT-->

        <div class="row-fluid">

            <div class="span12">

                <!-- BEGIN SAMPLE FORM PORTLET-->

                <div class="portlet box blue tabbable">

                    <div class="portlet-title">

                        <div class="caption">

                            <i class="icon-reorder"></i>

                            <span class="hidden-480">Create New Project</span>

                        </div>

                    </div>

                    <div class="portlet-body form">

                        <div class="tabbable portlet-tabs">

                            <ul class="nav nav-tabs">

                                <li class="active"><a href="#portlet_tab1" data-toggle="tab">Default</a></li>

                            </ul>

                            <div class="tab-content">

                                {%if user.email%}
                                <div class="tab-pane active" id="portlet_tab1">

                                    <!-- BEGIN FORM-->

                                    <form action="{% url 'management:new_project' %}" class="form-horizontal"
                                          method="post">
                                        {% csrf_token %}
                                        <div class="control-group">

                                            <label class="control-label">Project Name</label>

                                            <div class="controls">

                                                <input id="project_name" name="project_name" type="text"
                                                       placeholder="please input your project name"
                                                       class="m-wrap large"/>


                                            </div>

                                        </div>


                                        <div class="control-group">

                                            <label class="control-label">Project Description</label>

                                            <div class="controls">

                                                <textarea id="project_description" name="project_description"
                                                          class="large m-wrap" rows="3"></textarea>

                                            </div>

                                        </div>

                                        <div class="form-actions">

                                            <button type="submit" class="btn blue"><i class="icon-ok"></i> Save</button>

                                            <button type="button" id="cancle" class="btn">Cancel</button>

                                        </div>

                                    </form>

                                    <!-- END FORM-->

                                </div>
                                {%else%}
                                <div class="tab-pane active">

                                    <!-- BEGIN FORM-->

                                    <label>You have no permission to create a new project.</label>

                                    <!-- END FORM-->

                                </div>
                                {%endif%}

                            </div>

                        </div>

                    </div>

                </div>

                <!-- END SAMPLE FORM PORTLET-->

            </div>

        </div>

        <!-- END PAGE CONTENT-->

    </div>

    <!-- END PAGE CONTAINER-->

</div>
<script src="/static/media/js/jquery-1.10.1.min.js" type="text/javascript"></script>
<script src="/static/media/js/app.js" type="text/javascript"></script>
<script src="/static/media/js/bootstrap.min.js"></script>


<script>
	$("#cancle").click(function () {
		$("#project_name")[0].value="";
		$("#project_description")[0].value=""
	});


</script>

DragonCorpus/templates/new_testsuit_page_content.html
		<div class="page-content">

			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->

			<div id="portlet-config" class="modal hide">

				<div class="modal-header">

					<button data-dismiss="modal" class="close" type="button"></button>

					<h3>portlet Settings</h3>

				</div>

				<div class="modal-body">

					<p>Here will be a configuration form</p>

				</div>

			</div>

			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

			<!-- BEGIN PAGE CONTAINER-->

			<div class="container-fluid">

				<!-- BEGIN PAGE HEADER-->

				<div class="row-fluid">

					<div class="span12">

						<!-- BEGIN STYLE CUSTOMIZER -->

						{% include 'base/theme.html' %}

						<!-- END BEGIN STYLE CUSTOMIZER -->

						<h3 class="page-title">

							Add New Testsuit

							 <small></small>

						</h3>

						<ul class="breadcrumb">

							<li>

								<i class="icon-home"></i>

								<a href="{% url 'management:index'%}">Home</a>

								<span class="icon-angle-right"></span>

							</li>

							<li>

								<a href="#">New Testsuit</a>

								<span class="icon-angle-right"></span>

							</li>

							<li><a href="#">Add</a></li>

						</ul>

					</div>

				</div>

				<!-- END PAGE HEADER-->

				<!-- BEGIN PAGE CONTENT-->

				<div class="row-fluid">

					<div class="span12">

						<!-- BEGIN SAMPLE FORM PORTLET-->

						<div class="portlet box blue tabbable">

							<div class="portlet-title">

								<div class="caption">

									<i class="icon-reorder"></i>

									<span class="hidden-480">Create New Testsuit</span>

								</div>

							</div>

							<div class="portlet-body form">

								<div class="tabbable portlet-tabs">

									<ul class="nav nav-tabs">

										<li class="active"><a href="#portlet_tab1" data-toggle="tab">Default</a></li>

									</ul>

									<div class="tab-content">

										<div class="tab-pane active" id="portlet_tab1">

											<!-- BEGIN FORM-->

											<form action="{% url 'management:new_testsuit' %}" class="form-horizontal" method="post">
												{% csrf_token %}
												<div class="control-group">

													<label class="control-label">Testsuit Name</label>

													<div class="controls">

														<input id="testsuit_name" name="testsuit_name" type="text" placeholder="please input your testsuit name" class="m-wrap large" />

														<span class="help-inline">Please input your testsuit name</span>

													</div>

												</div>


												<div class="form-actions">

													<button type="submit" class="btn blue"><i class="icon-ok"></i> Save</button>

													<button type="button" class="btn">Cancel</button>

												</div>

											</form>

											<!-- END FORM-->

										</div>

									</div>

								</div>

							</div>

						</div>

						<!-- END SAMPLE FORM PORTLET-->

					</div>

				</div>

				<!-- END PAGE CONTENT-->

			</div>

			<!-- END PAGE CONTAINER-->

		</div>

<script src="/static/media/js/app.js" type="text/javascript"></script>
<script src="/static/media/js/bootstrap.min.js"></script>

DragonCorpus/templates/project_and_testsuit_overview_detail_page_content.html
<div class="page-content">

    <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->

    <!--<div id="portlet-config" class="modal hide">-->

    <!--<div class="modal-header">-->

    <!--<button data-dismiss="modal" class="close" type="button"></button>-->

    <!--<h3>portlet Settings</h3>-->

    <!--</div>-->

    <!--<div class="modal-body">-->

    <!--<p>Here will be a configuration form</p>-->

    <!--</div>-->

    <!--</div>-->

    <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

    <!-- BEGIN PAGE CONTAINER-->

    <div class="container-fluid">

        <!-- BEGIN PAGE HEADER-->

        <div class="row-fluid">

            <div class="span12">

                <!-- BEGIN STYLE CUSTOMIZER -->

                <!--{% include 'base/theme.html' %}-->

                <!-- END BEGIN STYLE CUSTOMIZER -->

                <h3 class="page-title">

                    ProjectAndTestsuit Overview

                    <small></small>

                </h3>

                <ul class="breadcrumb">

                    <li>

                        <i class="icon-home"></i>

                        <a href="{% url 'management:index'%}">Home</a>

                        <span class="icon-angle-right"></span>

                    </li>

                    <li>

                        <a href="#">Overview</a>

                        <span class="icon-angle-right"></span>

                    </li>

                    <li><a href="#">See More</a></li>

                </ul>

            </div>

        </div>

        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTANER-->

        <div class="row-fluid">

            <div class="span6">

                <div class="portlet box grey">

                    <div class="portlet-title">

                        <div class="caption"><i class="icon-comments"></i>Project Overview</div>


                    </div>

                    <div class="portlet-body fuelux">

                        <ul class="tree" id="tree_1">

                            <li>

                                <a href="#" data-role="branch" class="tree-toggle" data-toggle="branch"
                                   data-value="Bootstrap_Tree">

                                    Project

                                </a>

                                <ul class="branch in">
                                    {% for obj in project_list_all %}
                                    <li>

                                        <a href="{% url 'management:project_overview_detail' obj.id%}">
                                            <i class="icon-plane"></i>

                                            {{ obj.project_name }}</a>

                                    </li>
                                    {% endfor %}

                                </ul>

                            </li>

                        </ul>

                    </div>

                </div>

            </div>

            <div class="span6">

                <div class="portlet box grey">

                    <div class="portlet-title">

                        <div class="caption"><i class="icon-comments"></i>Testsuit Overview</div>

                    </div>

                    <div class="portlet-body fuelux">

                        <ul class="tree" id="tree_2">

                            <li>

                                <a href="#" data-role="branch" class="tree-toggle" data-toggle="branch"
                                   data-value="Bootstrap_Tree">Testsuit

                                </a>

                                <ul class="branch in">

                                    {% for obj in testsuit_list_all %}
                                    <li>

                                        <a href="{% url 'management:testsuit_overview_detail' obj.id%}">
                                            <i class="icon-suitcase"></i>

                                            {{ obj.testsuit_name }}</a>

                                    </li>
                                    {% endfor %}

                                </ul>

                            </li>

                        </ul>

                    </div>

                </div>

            </div>

        </div>

        <!-- END PAGE CONTENT-->

    </div>

    <!-- END PAGE CONTAINER-->

</div>
</div>