DragonCorpus/DragonCorpus/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^management/', include('management.urls',  namespace='management')),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

    # reset password
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete', ),
]

DragonCorpus/accounts/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from accounts import user
from accounts import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, PasswordResetForm
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', user.login, name='login'),
    url(r'^logout/$', user.logout, name='logout'),
    url(r'^change_password/$', user.change_password, name='change_password'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
]

DragonCorpus/management/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    #login
    url(r'^index/$',views.index,name='index'),
    url(r'^(?P<project_id>\w+)/project_overview_detail/$',views.project_overview_detail,name='project_overview_detail'),
    url(r'^project_overview_detail_table/$',views.project_overview_detail_table,name='project_overview_detail_table'),
    url(r'^testsuit_overview_detail_table/$', views.testsuit_overview_detail_table, name='testsuit_overview_detail_table'),
    url(r'^utterance_table/$', views.utterance_table, name='utterance_table'),
    url(r'^(?P<testsuit_id>\w+)/testsuit_overview_detail/$', views.testsuit_overview_detail,name='testsuit_overview_detail'),
    url(r'^new_project/$',views.new_project,name='new_project'),
    url(r'^new_testsuit/$',views.new_testsuit,name='new_testsuit'),
    url(r'^utterance/$', views.utterance, name='utterance'),
    url(r'^upload_hrl/$', views.upload_hrl, name='upload_hrl'),
    url(r'^project_and_testsuit_overview_detail/$', views.project_and_testsuit_overview_detail, name='project_and_testsuit_overview_detail'),
    #filter
    url(r'^get_all_intent/$', views.get_all_intent, name='get_all_intent'),
    url(r'^get_testsuit_all_intent/$', views.get_testsuit_all_intent, name='get_testsuit_all_intent'),

    #error
    url(r'^error_page/$', views.error_page, name='error_page'),

    #delete testsuit
    url(r'^delete_testsuit/$', views.delete_testsuit,name='delete_tesuit'),
    # add testSuit
    url(r'^add_testsuit/$', views.add_testsuit, name='add_testsuit'),
    # delete_testsuit_item
    url(r'^delete_testsuit_item/$', views.delete_testsuit_item, name='delete_testsuit_item'),
    #download_testsuit
    url(r'^download_testsuit/$', views.download_testsuit, name='download_testsuit'),
    url(r'^zip_download/$', views.zip_download, name='zip_download'),
    #upload audio
    url(r'^upload_utterance_table/$', views.upload_utterance_table, name='upload_utterance_table'),

]

DragonCorpus/templates/base/base.html
<!--{% load staticfiles %}-->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
	        {% include 'base/header.html' %}
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-sidebar-closed">
	<!-- BEGIN HEADER -->
	{% include 'base/navi.html' %}
	<!-- END HEADER -->
	<!-- BEGIN CONTAINER -->
	<div class="page-container">
		<!-- BEGIN SIDEBAR -->
		{% include 'base/page_sidebar.html' %}
		<!-- END SIDEBAR -->
		<!-- BEGIN PAGE -->
		 {% block content %}{% endblock %}
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
	        {% include 'base/footer.html' %}
	<!-- END FOOTER -->
	 {% include 'base/js.html' %}
</body>
<!-- END BODY -->
</html>

DragonCorpus/templates/base/base_index.html
<!--{% load staticfiles %}-->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
	        {% include 'base/header.html' %}
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed page-sidebar-closed">
	<!-- BEGIN HEADER -->
	{% include 'base/navi.html' %}
	<!-- END HEADER -->
	<!-- BEGIN CONTAINER -->
	<div class="page-container">
		<!-- BEGIN SIDEBAR -->
		{% include 'base/page_sidebar.html' %}
		<!-- END SIDEBAR -->
		<!-- BEGIN PAGE -->
		 {% block content %}{% endblock %}
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
	        {% include 'base/footer.html' %}
	<!-- END FOOTER -->
	 {% include 'base/index_js.html' %}
</body>
<!-- END BODY -->
</html>

DragonCorpus/templates/base/base_login.html
<!--{% load staticfiles %}-->
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
	        {% include 'base/header.html' %}
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">
	<!-- BEGIN HEADER -->
	{% include 'base/navi.html' %}
	<!-- END HEADER -->
	<!-- BEGIN CONTAINER -->
	<div class="page-container">
		<!-- BEGIN SIDEBAR -->
		<!-- END SIDEBAR -->
		<!-- BEGIN PAGE -->
		 {% block content %}{% endblock %}
		<!-- END PAGE -->
	</div>
	<!-- END CONTAINER -->
	<!-- BEGIN FOOTER -->
    {% include 'base/footer.html' %}
	<!-- END FOOTER -->
	 {% include 'base/js.html' %}
</body>
<!-- END BODY -->
</html>

DragonCorpus/templates/base/filter.html
<div class="span2">

						<!-- BEGIN SAMPLE FORM PORTLET-->

						<div class="portlet box blue tabbable">

							<div class="portlet-title">

								<div class="caption">

									<i class="icon-reorder"></i>

									<span class="hidden-480">General Layouts</span>

								</div>

							</div>

							<div class="portlet-body form">

								<div class="tabbable portlet-tabs">

									<ul class="nav nav-tabs">

										<li><a href="#portlet_tab3" data-toggle="tab">Inline</a></li>

										<li><a href="#portlet_tab2" data-toggle="tab">Grid</a></li>

										<li class="active"><a href="#portlet_tab1" data-toggle="tab">Default</a></li>

									</ul>

									<div class="tab-content">

										<div class="tab-pane active" id="portlet_tab1">

											<!-- BEGIN FORM-->

											<form action="#" class="form-horizontal">

												<div class="control-group">

													<label class="control-label">Small Input</label>

													<div class="controls">

														<input type="text" placeholder="small" class="m-wrap small" />

														<span class="help-inline">Some hint here</span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Meduam Input</label>

													<div class="controls">

														<input type="text" placeholder="medium" class="m-wrap medium" />

														<span class="help-inline">Some hint here</span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Large Input</label>

													<div class="controls">

														<input type="text" placeholder="large" class="m-wrap large" />

														<span class="help-inline">Some hint here</span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Huge Input</label>

													<div class="controls">

														<input type="text" placeholder="huge" class="m-wrap huge" />

														<span class="help-inline">Some hint here</span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Disabled Input</label>

													<div class="controls">

														<input class="m-wrap medium" type="text" placeholder="Disabled input here..." disabled />

														<span class="help-inline">Some hint here</span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Readonly Input</label>

													<div class="controls">

														<input class="m-wrap medium" readonly type="text" placeholder="Readonly input here..." disabled />

														<span class="help-inline">Some hint here</span>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Small Dropdown</label>

													<div class="controls">

														<select class="small m-wrap" tabindex="1">

															<option value="Category 1">Category 1</option>

															<option value="Category 2">Category 2</option>

															<option value="Category 3">Category 5</option>

															<option value="Category 4">Category 4</option>

														</select>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Medium Dropdown</label>

													<div class="controls">

														<select class="medium m-wrap" tabindex="1">

															<option value="Category 1">Category 1</option>

															<option value="Category 2">Category 2</option>

															<option value="Category 3">Category 5</option>

															<option value="Category 4">Category 4</option>

														</select>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Large Dropdown</label>

													<div class="controls">

														<select class="large m-wrap" tabindex="1">

															<option value="Category 1">Category 1</option>

															<option value="Category 2">Category 2</option>

															<option value="Category 3">Category 5</option>

															<option value="Category 4">Category 4</option>

														</select>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Radio Buttons</label>

													<div class="controls">

														<label class="radio">

														<input type="radio" name="optionsRadios1" value="option1" />

														Option 1

														</label>

														<label class="radio">

														<input type="radio" name="optionsRadios1" value="option2" checked />

														Option 2

														</label>

														<label class="radio">

														<input type="radio" name="optionsRadios1" value="option2" />

														Option 3

														</label>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Radio Buttons</label>

													<div class="controls">

														<label class="radio line">

														<input type="radio" name="optionsRadios2" value="option1" />

														Option 1

														</label>

														<label class="radio line">

														<input type="radio" name="optionsRadios2" value="option2" checked />

														Option 2

														</label>

														<label class="radio line">

														<input type="radio" name="optionsRadios2" value="option2" />

														Option 3

														</label>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Checkbox</label>

													<div class="controls">

														<label class="checkbox">

														<input type="checkbox" value="" /> Checkbox 1

														</label>

														<label class="checkbox">

														<input type="checkbox" value="" /> Checkbox 2

														</label>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Checkbox</label>

													<div class="controls">

														<label class="checkbox line">

														<input type="checkbox" value="" /> Checkbox 1

														</label>

														<label class="checkbox line">

														<input type="checkbox" value="" /> Checkbox 2

														</label>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Textarea</label>

													<div class="controls">

														<textarea class="medium m-wrap" rows="3"></textarea>

													</div>

												</div>

												<div class="control-group">

													<label class="control-label">Large Textarea</label>

													<div class="controls">

														<textarea class="large m-wrap" rows="3"></textarea>

													</div>

												</div>

												<div class="form-actions">

													<button type="submit" class="btn blue"><i class="icon-ok"></i> Save</button>

													<button type="button" class="btn">Cancel</button>

												</div>

											</form>

											<!-- END FORM-->

										</div>

										<div class="tab-pane " id="portlet_tab2">

											<form>

												<div class="controls controls-row">

													<input class="span12 m-wrap" type="text" placeholder=".span12" />

												</div>

												<div class="controls controls-row">

													<input class="span11 m-wrap" type="text" placeholder=".span11" />

													<input class="span1 m-wrap" type="text" placeholder=".span1" />

												</div>

												<div class="controls controls-row">

													<input class="span10 m-wrap" type="text" placeholder=".span10" />

													<input class="span2 m-wrap" type="text" placeholder=".span2" />

												</div>

												<div class="controls controls-row">

													<input class="span9 m-wrap" type="text" placeholder=".span9" />

													<input class="span3 m-wrap" type="text" placeholder=".span3" />

												</div>

												<div class="controls controls-row">

													<input class="span8 m-wrap" type="text" placeholder=".span8" />

													<input class="span4 m-wrap" type="text" placeholder=".span4" />

												</div>

												<div class="controls controls-row">

													<input class="span7 m-wrap" type="text" placeholder=".span7" />

													<input class="span5 m-wrap" type="text" placeholder=".span5" />

												</div>

												<div class="controls controls-row">

													<input class="span6 m-wrap" type="text" placeholder=".span6" />

													<input class="span6 m-wrap" type="text" placeholder=".span6" />

												</div>

												<div class="controls controls-row">

													<input class="span5 m-wrap" type="text" placeholder=".span5" />

													<input class="span7 m-wrap" type="text" placeholder=".span7" />

												</div>

												<div class="controls controls-row">

													<input class="span4 m-wrap" type="text" placeholder=".span4" />

													<input class="span8 m-wrap" type="text" placeholder=".span8" />

												</div>

												<div class="controls controls-row">

													<input class="span3 m-wrap" type="text" placeholder=".span3" />

													<input class="span9 m-wrap" type="text" placeholder=".span9" />

												</div>

												<div class="controls controls-row">

													<input class="span2 m-wrap" type="text" placeholder=".span2" />

													<input class="span10 m-wrap" type="text" placeholder=".span10" />

												</div>

												<div class="controls controls-row">

													<input class="span1 m-wrap" type="text" placeholder=".span1" />

													<input class="span11 m-wrap" type="text" placeholder=".span11" />

												</div>

												<div class="controls controls-row">

													<input class="span2 m-wrap" type="text" placeholder=".span2" />

													<input class="span3 m-wrap" type="text" placeholder=".span3" />

													<input class="span4 m-wrap" type="text" placeholder=".span4" />

													<input class="span2 m-wrap" type="text" placeholder=".span2" />

													<input class="span1 m-wrap" type="text" placeholder=".span1" />

												</div>

											</form>

										</div>

										<div class="tab-pane " id="portlet_tab3">

											<h4>Login Form</h4>

											<form action="#">

												<input type="text" class="m-wrap" placeholder="Email" /><br />

												<input type="password" class="m-wrap" placeholder="Password" />

												<label class="checkbox">

												<input type="checkbox" /> Remember me

												</label>

												<button type="submit" class="btn green">Sign in</button>

											</form>

											<hr />

											<h4>Login Form</h4>

											<form action="#">

												<div class="input-icon left">

													<i class="icon-envelope"></i>

													<input type="text" class="m-wrap" placeholder="Email" />

												</div>

												<div class="input-icon left">

													<i class="icon-lock"></i>

													<input type="password" class="m-wrap" placeholder="Password" />

												</div>

												<label class="checkbox">

												<input type="checkbox" /> Remember me

												</label>

												<button type="submit" class="btn purple">Sign in</button>

											</form>

											<hr />

											<form action="#">

												<div class="input-prepend">

													<button class="btn blue">Login</button><input class="m-wrap" size="16" type="password" placeholder="Your Password" />

												</div>

											</form>

											<h4>Search Form</h4>

											<form action="#">

												<div class="input-append hidden-phone">

													<input class="m-wrap medium" size="10" type="text" placeholder="Twitter Username" /><button class="btn red">Search</button><button class="btn black">Back</button>

												</div>

												<div class="input-append visible-phone">

													<input class="m-wrap" size="10" type="text" placeholder="Twitter Username" /><button class="btn red">Search</button><button class="btn black">Back</button>

												</div>

											</form>

											<hr />

											<form action="#" class="form-search">

												<div class="input-append">

													<input class="m-wrap" type="text" /><button class="btn green" type="button">Search!</button>

												</div>

											</form>

										</div>

									</div>

								</div>

							</div>

						</div>

						<!-- END SAMPLE FORM PORTLET-->

					</div>

DragonCorpus/templates/base/footer.html
<div class="footer">

		<div class="footer-inner">
			2018 Nuance QA - Dragon Corpus
		</div>

		<div class="footer-tools">

			<span class="go-top">

			<i class="icon-angle-up"></i>

			</span>

		</div>

	</div>

DragonCorpus/templates/base/header.html
<head>

	<meta charset="utf-8" />

	<title>Dragon Corpus</title>

	<meta content="width=device-width, initial-scale=1.0" name="viewport" />

	<meta content="" name="description" />

	<meta content="" name="author" />

	<!-- BEGIN GLOBAL MANDATORY STYLES -->

	<link href="/static/media/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/style-metro.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/style.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/style-responsive.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/default.css" rel="stylesheet" type="text/css" id="style_color"/>

	<link href="/static/media/css/uniform.default.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/jquery.fancybox.css" rel="stylesheet" />

	<link href="/static/media/css/jquery.fileupload-ui.css" rel="stylesheet" />

	<link rel="stylesheet" type="text/css" href="/static/media/css/bootstrap-fileupload.css" />

	<!-- END GLOBAL MANDATORY STYLES -->

	<!-- BEGIN PAGE LEVEL STYLES -->
	<link rel="stylesheet" type="text/css" href="/static/media/css/chosen.css" />

	<link rel="stylesheet" type="text/css" href="/static/media/css/select2_metro.css" />

	<link href="/static/media/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>

	<link href="/static/media/css/daterangepicker.css" rel="stylesheet" type="text/css" />


	<link href="/static/media/css/jqvmap.css" rel="stylesheet" type="text/css" media="screen"/>

	<link href="/static/media/css/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>

	<link rel="stylesheet" type="text/css" href="/static/media/css/select2.css" />

	<!--<link rel="stylesheet" href="/static/media/css/DT_bootstrap.css" />-->

	<link rel="stylesheet" href="/static/bootstrap-table/bootstrap-table.min.css" />

	<link rel="stylesheet" type="text/css" href="/static/media/css/multi-select-metro.css" />

	<link rel="stylesheet" type="text/css" href="/static/media/css/bootstrap-tree.css" />

	<link rel="stylesheet" type="text/css" href="/static/bootstrap-table/bootstrap-editable.css" />

	<!-- END PAGE LEVEL STYLES -->

	<link rel="shortcut icon" href="/static/media/image/favicon.ico" />

</head>

DragonCorpus/templates/base/js.html
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

	<!-- BEGIN CORE PLUGINS -->

	<script src="/static/media/js/jquery-1.10.1.min.js" type="text/javascript"></script>

	<script src="/static/media/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

	<!-- IMPORTANT! Load jquery-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->

	<script src="/static/media/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>

	<!--<script src="/static/media/js/bootstrap.min.js" type="text/javascript"></script>-->

	<!--[if lt IE 9]>

	<script src="/static/media/js/excanvas.min.js"></script>

	<script src="/static/media/js/respond.min.js"></script>

	<![endif]-->

	<!-- END CORE PLUGINS -->

	<!-- BEGIN PAGE LEVEL PLUGINS -->


	<script type="text/javascript" src="/static/media/js/chosen.jquery.min.js"></script>

	<script type="text/javascript" src="/static/media/js/select2.min.js"></script>

	<script type="text/javascript" src="/static/media/js/jquery.multi-select.js"></script>

	<script type="text/javascript" src="/static/media/js/bootstrap-fileupload.js"></script>

    <script src="/static/media/js/bootstrap-tree.js"></script>

	<!-- END PAGE LEVEL PLUGINS -->

	<!-- BEGIN PAGE LEVEL SCRIPTS -->
    <!--<script src="/static/media/js/app.js"></script>-->

	<!--<script src="/static/media/js/app.js" type="text/javascript"></script>-->

	<script src="/static/media/js/index.js" type="text/javascript"></script>

	<script src="/static/bootstrap-table/bootstrap-table.js"></script>


	<!-- END PAGE LEVEL SCRIPTS -->

	<script>

		jQuery(document).ready(function() {


		   App.init(); // initlayout and core plugins

		   Index.init();

		   <!--Index.initJQVMAP(); // init index page's custom scripts-->

		   <!--Index.initCalendar(); // init index page's custom scripts-->

		   <!--Index.initCharts(); // init index page's custom scripts-->

		   <!--Index.initChat();-->

		   <!--Index.initMiniCharts();-->

		   <!--Index.initDashboardDaterange();-->

		   <!--Index.initIntro();-->

		   <!--UITree.init();-->

		});


	</script>

	<!-- END JAVASCRIPTS -->

DragonCorpus/templates/base/navi.html
<div class="header navbar navbar-inverse navbar-fixed-top">

		<!-- BEGIN TOP NAVIGATION BAR -->

		<div class="navbar-inner">

			<div class="container-fluid">

				<!-- BEGIN LOGO -->

				<a class="brand" href="">

				<img src="/static/media/image/logo-big.png" alt="logo"/>

				</a>

				<!-- END LOGO -->

				<!-- BEGIN RESPONSIVE MENU TOGGLER -->

				<a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">

				<img src="/static/media/image/menu-toggler.png" alt="" />

				</a>

				<!-- END RESPONSIVE MENU TOGGLER -->
				<!-- BEGIN TOP NAVIGATION MENU -->
				<ul class="nav pull-right">
					<!-- END TODO DROPDOWN -->
					<!-- BEGIN USER LOGIN DROPDOWN -->
					<li class="dropdown user">

						<a href="#" class="dropdown-toggle" data-toggle="dropdown">

						<!--<img alt="" src="/static/media/image/avatar1_small.jpg" />-->

						<span class="username">{{user.username}}</span>

						<i class="icon-angle-down"></i>

						</a>

						<ul class="dropdown-menu">
							{% if user.username%}
							<li><a href="{% url 'accounts:logout' %}"><i class="icon-key"></i> Log Out</a></li>
							{% else %}
							<li><a href="{% url 'accounts:login' %}"><i class="icon-key"></i> Log In</a></li>
							{% endif %}
						</ul>
					</li>

					<!-- END USER LOGIN DROPDOWN -->

				</ul>
				<!-- END TOP NAVIGATION MENU -->

			</div>

		</div>

		<!-- END TOP NAVIGATION BAR -->

	</div>

DragonCorpus/templates/base/page_sidebar.html
<div class="page-sidebar nav-collapse collapse">

			<!-- BEGIN SIDEBAR MENU -->

			<ul class="page-sidebar-menu">

				<li>

					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->

					<div class="sidebar-toggler hidden-phone"></div>

					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->

				</li>

				<li style="height:16px">

					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->


					<!-- END RESPONSIVE QUICK SEARCH FORM -->

				</li>

				<li class="start active ">

					<a href="{% url 'management:index'%}">

					<i class="icon-home"></i>

					<span class="title" >Dashboard</span>

					<!--<span class="selected"></span>-->

					</a>

				</li>

					<li>

					<a href="javascript:;">

					<i class="icon-sitemap"></i>

					<span class="title">Create</span>

					<span class="arrow "></span>

					</a>
						<ul class="sub-menu">
						<li >
							<a href="{% url 'management:new_project'%}">
							Project</a>
						</li>

					</ul>

				</li>

				<li class="">

					<a href="javascript:;">

					<i class="icon-cogs"></i>

					<span class="title" >Project Overview</span>

					<span class="arrow "></span>

					</a>

					<ul class="sub-menu">
						 {% for obj in project_list %}
						<li >

							<a href="{% url 'management:project_overview_detail' obj.id%}">

							{{ obj.project_name }}</a>

						</li>
						   {% endfor %}
						<li >

							<a href="{% url 'management:project_and_testsuit_overview_detail' %}">

							See More</a>

						</li>

					</ul>
				</li>




				<li class="">

					<a href="javascript:;">

					<i class="icon-th"></i>

					<span class="title">Testsuit Overview</span>

					<span class="arrow "></span>

					</a>

					<ul class="sub-menu">

                        {% for obj in testsuit_list %}
						<li >

							<a href="{% url 'management:testsuit_overview_detail' obj.id%}">

							{{obj.testsuit_name}}</a>

						</li>
						{% endfor %}
						<li >

							<a href="{% url 'management:project_and_testsuit_overview_detail' %}">

							See More</a>

						</li>

					</ul>

				</li>

				<li class="">

					<a href="javascript:;">

					<i class="icon-bookmark-empty"></i>

					<span class="title">Config management</span>

					<span class="arrow "></span>

					</a>

					<ul class="sub-menu">

						<li >

							<a href="ui_general.html">

							Project1_config</a>

						</li>

						<li >

							<a href="ui_buttons.html">

							Project2_config</a>

						</li>

						<li >

							<a href="ui_modals.html">

							Project3_config</a>

						</li>

						<li >

							<a href="ui_tabs_accordions.html">

							Project4_config</a>

						</li>

						<li >

							<a href="ui_jqueryui.html">

							Project5_config</a>

						</li>

					</ul>

				</li>

				<li>

					<a href="{% url 'management:utterance'%}">

					<i class="icon-folder-open"></i>

					<span class="title">Utterance</span>

					<span class="arrow "></span>

					</a>

				</li>

			</ul>

			<!-- END SIDEBAR MENU -->

		</div>